<?php

namespace AppBundle\Repository;

/**
 * HealthProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
