<?php

namespace AppBundle\Repository;

/**
 * MealTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
