<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser(User $user){
        $qb = $this->createQueryBuilder('m')
            ->join('m.user', 'u')
            ->where('m.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $qb->getResult();
    }
}
